name: My First workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Welcome message
          run : echo "My first Github Action"
       
        - name: List and Read file
          run: | 
            echo "My first Github Action"
            ls -ltra
            cat README.md

        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for cover, I am i DRAGON....RAWR" >> dragon.txt
        
     


